name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: apt update
      run: sudo apt update
    - name: apt install
      run: sudo apt install -y liblzo2-dev mtd-utils squashfs-tools fakeroot
    - name: pipx upgrade
      run: sudo python -m pip install --upgrade pip --break-system-packages
    - name: pipx install
      run: pip install python-lzo ubi_reader
    - name: make
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: miwifi_r3600_all_6510e_3.0.22_INT_SSH.bin
        path: miwifi_r3600_all_6510e_3.0.22_INT_SSH.bin
