name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt update
      run: sudo apt update
    - name: apt install
      run: sudo apt install -y liblzo2-dev mtd-utils squashfs-tools fakeroot
    - name: pip upgrade
      run: python -m pip install --upgrade pip
    - name: pip install
      run: pip install python-lzo ubi_reader
    - name: make
      run: sudo ./repack-squashfs.sh
    - name: make
      run: sudo ./ubinize.sh
    - uses: actions/upload-artifact@v4
      with:
        name: r3600-raw-img.bin
        path: r3600-raw-img.bin
