name: CI

on: 
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt update
      run: sudo apt update
    - name: apt install
      run: sudo apt install -y liblzo2-dev mtd-utils squashfs-tools fakeroot
    - name: pip upgrade
      run: python -m pip install --upgrade pip
    - name: pip install
      run: pip install python-lzo ubi_reader
    - name: make
      run: make all

    - uses: actions/upload-artifact@v3
      with:
        name: miwifi_r3600_all_6510e_3.0.22_INT_AX3600_SSH.bin
        path: miwifi_r3600_all_6510e_3.0.22_INT_AX3600_SSH.bin

    - uses: actions/upload-artifact@v3
      with:
        name: miwifi_ra72_firmware_129d1_1.0.103_AX6000_SSH.bin
        path: miwifi_ra72_firmware_129d1_1.0.103_AX6000_SSH.bin
